# Generated by Django 5.1 on 2024-11-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=45)),
                ('prioridade', models.CharField(max_length=45)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='users.user')),
            ],
        ),
    ]
